black_primary_font = '#ffd'
black_primary_background = 'g10'
black_p_tertiary_font = 'g40'
black_secondary_font = '#aa8'
black_secondary_background = 'g05'
black_s_tertiary_font = 'g35'

dark_grey_primary_font = '#dff'
dark_grey_primary_background = 'g20'
dark_grey_p_tertiary_font = 'g40'
dark_grey_secondary_font = '#8aa'
dark_grey_secondary_background = 'g15'
dark_grey_s_tertiary_font = 'g35'

grey_primary_font = 'g90'
grey_primary_background = 'g30'
grey_p_tertiary_font = 'g90'
grey_secondary_font = 'g70'
grey_secondary_background = 'g25'
grey_s_tertiary_font = 'g70'
